name: 'Eth security toolbox'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
runs:
  using: 'docker'
  image: 'trailofbits/eth-security-toolbox'
  working-directory: 'ethereum/kycdao-ntnft'
