name: Ethereum
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  buildandtestandcoverageandanalyzer:
    name: build, test, coverage and analyzer
    defaults:
      run:
        working-directory: ethereum/kycdao-ntnft
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ethereum/kycdao-ntnft/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Compile
      run: npm run compile
    - name: Run tests
      run: npm test
#    - run: npm run testGsn
    - name: Generate solidity coverage reports
      run: node --max-old-space-size=4096 ./node_modules/.bin/hardhat coverage
    - name: Upload reports to codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: | 
       curl -Os https://uploader.codecov.io/latest/linux/codecov
       find . -iregex "codecov.*"
       chmod +x codecov 
       ./codecov -t ${CODECOV_TOKEN}  
    - name: Slither analyze code
      run: |
        pip3 install slither-analyzer
        slither --no-fail-pedantic --disable-color --sarif results.sarif .
        slither --no-fail-pedantic --disable-color --ignore-compile --print human-summary .
    - name: Upload sarif results
      uses: actions/upload-artifact@v3
      with:
        name: results.sarif
        path: ethereum/kycdao-ntnft/results.sarif
        retention-days: 90
