name: Near
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  buildandtest:
    name: build, test
    defaults:
      run:
        working-directory: near/kycdao-ntnft
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        dir: near/kycdao-ntnft
        cmd: install
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        args: --manifest-path near/kycdao-ntnft/Cargo.toml
        command: test
