name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" 
jobs:
  build:
    defaults:
      run:
        working-directory: ethereum/kycdao-ntnft
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ethereum/kycdao-ntnft/package-lock.json
    - run: npm ci
    - run: npm run compile
    - run: npm test
    - run: npm run testGsn
    - run: node --max-old-space-size=4096 ./node_modules/.bin/hardhat coverage
    - run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov
      with:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
