name: Ethereum Code Analyzer
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  buildandtest:
    name: slither code analyzer
    defaults:
      run:
        working-directory: ethereum/kycdao-ntnft
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Slither
      uses: crytic/slither-action@v0.2.0
      id: slither
      with:
        node-version: 16
        target: ethereum/kycdao-ntnft
        sarif: results.sarif
        fail-on: high
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
